# Generated by Django 3.2 on 2021-05-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eShopUser', '0002_remove_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50, null=True),
        ),
    ]
