# Generated by Django 3.2 on 2021-06-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eShopUser', '0005_auto_20210531_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
