# Generated by Django 3.2 on 2021-06-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eShopUser', '0006_auto_20210601_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
