# Generated by Django 3.2 on 2021-05-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eShopAdmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
