# Generated by Django 3.1.3 on 2021-02-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=8)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('photo', models.ImageField(null=True, upload_to='patient/imgs')),
            ],
        ),
    ]
