# Generated by Django 3.1.3 on 2021-02-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregister',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patientregister',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
